### ISSUE TITLE
No such file or directory: 'req.txt'

### ISSUE THREAD

**Issue by xiaoxiaoleo** [xionsec/WebXploiter#5]
root@kali:~/Desktop# cd WebXploiter/
root@kali:~/Desktop/WebXploiter# ls
fuzzdatabase  install  LICENSE  Modules  README.md  Recon  WebXploiter.py
root@kali:~/Desktop/WebXploiter# python install/install.py 
Traceback (most recent call last):
  File "install/install.py", line 39, in <module>
    main()
  File "install/install.py", line 34, in main
    install.install_os_tools()
  File "install/install.py", line 27, in install_os_tools
    install_file = open(self.os_install_tools, "r")
IOError: [Errno 2] No such file or directory: 'req.txt'

**Comment by a0xnirudh** [comment]
Instead of running python install/install.py, go to the folder install and then run python install.py  which will fix the issue as of now. Will push a permanent fix for it soon !
